#!/bin/sh

. /etc/ovpkg.conf

# Make tmpfs overlay dir if needed
if [ ! -d /tmp/overlay ]; then
	mkdir /tmp/overlay
fi

# Make tmpfs overlay status if needed
if [ ! -f /tmp/overlay/status ]; then
	echo 0 > /tmp/overlay/status
fi

# Check status to see if we are mounted
STATUS=`cat /tmp/overlay/status`
if [ $STATUS -eq 1 ]; then
	echo "Overlayfs already mounted"
	exit 1
fi

for rootfs in $SD_ROOTFS; do

	# Setup loop device
	if [ -f "/$rootfs" ]; then
		LOOPDEV=`losetup -f`
		echo "Creating ext2 loop device $LOOPDEV"
		losetup -o32256 ${LOOPDEV} $rootfs
		echo "Checking loop device for errors"
		e2fsck -y ${LOOPDEV}

		mount -t ext2 ${LOOPDEV} /overlay

		# Write status
		echo 1 > /tmp/overlay/status
		echo "$LOOPDEV" > /tmp/overlay/loopdevice

		# Run ldconfig
		ldconfig 2>/dev/null
		exit 0
	fi
done
	
echo "SD Card rootfs not found"
exit 1
