#!/bin/sh

# include ovpkg config file
. /etc/ovpkg.conf

# Make tmpfs overlay dir if needed
if [ ! -d /tmp/overlay ]; then
	mkdir /tmp/overlay
fi

# Make tmpfs overlay status if needed
if [ ! -f /tmp/overlay/status ]; then
	echo 0 > /tmp/overlay/status
fi

# Make sure overlay is mounted before installing
STATUS=`cat /tmp/overlay/status`
if [ $STATUS -ne 1 ]; then
	echo "Overlay not mounted, Exiting."
	exit 1
fi

# install packages
opkg -d card $@

# Run ldconfig
ldconfig 2>/dev/null

# Create gmenu2x launchers
ovlaunchers
